### ISSUE TITLE
DLL error when loading Bedrock maps

### ISSUE THREAD

**Issue by amg-12** [tryashtar/image-map#124]
On choosing a world, I get this error:
```
System.DIINotFoundException: Unable to load DLL 'leveldb' or one of its
dependencies: The specified module could not be found. (0x8007007E)
  at LevelDBWrapper.NativeMethods.leveldb_options_create()
  at LevelDBWrapper.Options..ctor()
  at ImageMap4.BedrockWorld.OpenDB()
  at ImageMap4.BedrockWorld.GetInventories()+MoveNext()
  at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
  at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
  at ImageMap4.MainViewModel.set_SelectedWorld(World value)
  at ImageMap4.MainWindow.TryOpenWorld(World world)
```
The files are extracted and the DLL is present. I'm Minecraft Education Edition (Bedrock based).

**Comment by amg-12** [comment]
Works fine on my other machine.
