### ISSUE TITLE
java no work

### ISSUE THREAD

**Issue by EpicGodFrogs74** [tryashtar/image-map#42]
when i click on java world in image map 2, it says "unhandled exception has occurred in your applicatioon"

**Comment by tryashtar** [comment]
Please post a screenshot or text of the exception details

**Comment by EpicGodFrogs74** [comment]
Here: ystem.NullReferenceException: Object reference not set to an instance of an object.
   at Image_Map.WorldControl..ctor(String worldfolder, Edition edition)
   at Image_Map.WorldWindow.LoadWorlds(String savesfolder)
   at Image_Map.WorldWindow.Show(Form parent)
   at Image_Map.TheForm.OpenWorldWithMessage(Edition edition)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by tryashtar** [comment]
Thanks, I think this is now fixed. Give this version a try and let me know: https://github.com/tryashtar/image-map/releases/tag/v1.14

**Comment by EpicGodFrogs74** [comment]
it work!
